MPESA_2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stk.urls'))
]

stk/urls.py
from django.contrib import admin
from django.urls import path,include
from  . import views

app_name = "stk"
urlpatterns = [
    path('pay/', views.pay,name="pay"),
    path('stkpush/', views.stkpush, name="stkpush")
]

stk/models.py
from django.db import models

# Create your models here.

stk/views.py
import requests
from django.shortcuts import render, HttpResponse

from .credentials import MpesaPpassword, MpesaAccessToken


# Create your views here.


def pay(request):
    return render(request, 'pay.html')


def stkpush(request):
    if request.method == 'POST':
        phone = request.POST['phone']
        amount = request.POST['amount']
        access_token = MpesaAccessToken.validated_access_token
        api_url = 'https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest'
        headers = {"Authorization": "Bearer %s" % access_token}
        request = {
                   "BusinessShortCode": MpesaPpassword.short_code,
                   "Password": MpesaPpassword.decoded,
                   "Timestamp": MpesaPpassword.pay_time,
                   "TransactionType": "CustomerPayBillOnline",
                   "Amount": amount,
                   "PartyA": phone,
                   "PartyB": MpesaPpassword.short_code,
                   "PhoneNumber": phone,
                   "CallBackURL": "https://sandbox.safaricom.co.ke/mpesa/",
                   "AccountReference": "Web Development",
                   "TransactionDesc": "Web Development Charges"
                }
        response = requests.post(api_url, json=request, headers=headers)
    return HttpResponse("success")

stk/templates/pay.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<form action="{% url 'stk:stkpush' %}" method="POST">
    {% csrf_token %}

    <input type="number"  value="254" name="phone">
    <input type="number" placeholder="Amount" name="amount">

    <input type="submit" value="Pay Now">
</form>

</body>
</html>